version: '3.1'

services :

  mysql :
    build : mysql
    restart : always
    ports: 
      - 3306:3306
    networks : 
      - calcnet
#  adminer :
#    image : adminer
#    restart : always
#    ports :
#      - 8080:8080
#    networks : 
#      - calcnet

  redis :
    image : redis:3.2-alpine
    restart: always
    ports: 
      - 6379:6379
    networks : 
      - calcnet
  
  bata : 
    build : bata
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379    
    networks : 
      - calcnet
    depends_on: 
      - mysql
      - redis

  tata : 
    build : tata
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379     
    networks : 
      - calcnet
    depends_on: 
      - mysql
      - redis
  
  calcindex :
    build : calcindex
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379        
    networks :
      - calcnet
    depends_on: 
      - mysql
      - redis
      - bata
      - tata

  ui :
    build : ui
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379  
    ports: 
      - 5000:5000
    networks :
      - calcnet
    depends_on: 
      - mysql
      - redis
      - bata
      - tata      

networks :
  calcnet :